"use client";

import "./../globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./component/sidebar";
import HeaderDashboard from "./component/header";
import Dashboard from "./component/dashboardContainer";
import styleDashboard from "./component/dashboardContainer/styleDashboard.module.css";
import { useEffect, useState } from "react";
import axios from "axios";
import { useRouter } from "next/navigation";
import Cookies from "js-cookie";
import jsHttpCookie from "cookie";
import { NextRequest } from "next/server";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// DashboardLayout.getInitialProps = ({ req }) => {
//   console.log("initialProp");
//   const initProps = {
//     token: null,
//   };

//   if (req && req.headers) {
//     const cookies = req.headers.cookie;
//     console.log(cookies, "cookies");

//     if (typeof cookies === "string") {
//       const cookiesJSON = jsHttpCookie.parse(cookies);

//       initProps.token = cookiesJSON.token;
//     }
//   }
// };

export default function DashboardLayout({ children }) {
  console.log("masuk layour dashboard");
  let router = useRouter();
  let token;
  let user;

  try {
    token = localStorage.getItem("token");
    user = JSON.parse(localStorage.getItem("user")); //untuk ubah dari string ke obj
    console.log(localStorage.getItem("token"), typeof user, "tokendd");
  } catch (err) {
    console.log("gak dapet token");
  }

  return (
    <div className={inter.className}>
      {/* {token && user.role === "asesi" ? ( */}
      <div className={`${styleDashboard.boxContainer}`}>
        <Sidebar />
        <div className={`${styleDashboard.boxContent}`}>
          <HeaderDashboard />
          <div className={`${styleDashboard.content}`}>{children}</div>
        </div>
      </div>
      {/* ) : (
        router.push("/login")
      )} */}
    </div>
  );
}
