import "./../globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./component/sidebar";
import HeaderDashboard from "./component/header";
import Dashboard from "./component/dashboardContainer";
import styleDashboard from "./component/dashboardContainer/styleDashboard.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // console.log({ children }, "children");
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={`${styleDashboard.boxContainer}`}>
          <Sidebar />
          <div className={`${styleDashboard.boxContent}`}>
            <HeaderDashboard />
            <div className={`${styleDashboard.content}`}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
